version: "2.1"
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@4.1.0
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - checkout
      - run:
          name: Install API Dependencies
          command: |
            npm run api:install
      - run:
          name: API Build
          command: |
            npm run api:build
      - run:
          name: Deploy API
          command: |
            npm run api:deploy
