version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            cd starter && npm run frontend:install
      - run:
          name: Install api Dependencies
          command: |
            cd starter && npm run api:install
      - run:
          name: Front-End Lint
          command: |
            cd starter && npm run frontend:lint
      - run:
          name: Front-End Build
          command: |
            cd starter && npm run frontend:build
      - run:
          name: Api Build
          command: |
            cd starter && npm run api:build
